### ISSUE TITLE
Script does not seem to work in Google Chrome

### ISSUE THREAD

**Issue by Niphanos** [coryshaw1/saliens-hack#14]
I noticed this error in the console. After reading the other issues, I read several requests for any errors in the console, so here you go. As for symptoms, there's no evidence of the Script running other than the Tampermonkey menu showing it active, and this error in the console.

```
VM528:62 Syntax error @ "Saliens Hack"!
##########################
JSHINT output:
##########################

SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Object.E_c (<anonymous>:3:304)
    at ka (eval at exec_fn (:1:107), <anonymous>:61:380)
    at Object.create (eval at exec_fn (:1:107), <anonymous>:72:334)
    at e (eval at exec_fn (:1:107), <anonymous>:16:157)
(anonymous) @ VM528:62
Uncaught SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Object.E_c (<anonymous>:3:304)
    at ka (eval at exec_fn ((index):1), <anonymous>:61:380)
    at Object.create (eval at exec_fn ((index):1), <anonymous>:72:334)
    at e (eval at exec_fn ((index):1), <anonymous>:16:157)
```

**Comment by Abrynos** [comment]
works for me

no problems here

**Comment by Sulizab** [comment]
All works fine, just load page "https://steamcommunity.com/saliengame/play/" and wait some seconds.

**Comment by krynv** [comment]
All fine here too

**Comment by coryshaw1** [comment]
This looks like you're running the script different. Are you using the userscript or pasting the script into the console window? Try disabling your ad blocker on Steam's site if you have one.

**Comment by Niphanos** [comment]
Cory, I'm running the userscript through Tampermonkey; not pasting it into the console. I disabled my adblocker and nothing seems to have changed.

**Comment by Niphanos** [comment]
Apparently the issue is with how I added it to Tampermonkey. There was apparently some uncommented text at the beginning and end, and removing that seems to have completely fixed it.

All I did to install it was save the .js file provided on the main page of this github and load it into Tampermonkey. Anyway, this fixed my problem and now it's working like a charm.
