### ISSUE TITLE
How to install it ? :D

### ISSUE THREAD

**Issue by TheIntelloBox** [coryshaw1/saliens-hack#34]
Hey ! :D 

I have installed Tampermonkey and the script, but where must I put the script to work ? :D 

Thanks for your answer. :)

**Comment by HiveSolution** [comment]
With Tampermonkey installed you just need to visit the raw user.js file here:

https://github.com/coryshaw1/saliens-hack/blob/master/saliensHack.user.js

It should open a install dialog. Click install and visit the game page. Everything should now be automated.

**Comment by TheIntelloBox** [comment]
Thanks a lot ! :D
