### ISSUE TITLE
This hack safe for my account ?

### ISSUE THREAD

**Issue by MikhaelLauda** [coryshaw1/saliens-hack#40]
Can i get VAC ban or ban if i use this ?

**Comment by mohamedawad12** [comment]
i wanna know to :"(

**Comment by coryshaw1** [comment]
This is safe. There are have been hacks for every Steam Sale game so far. Take a look into the 2015 monster mini game from that Steam Sale. There were crazy hacks for that one too. Ultimately it is up to you, but from my experience I have never heard of a ban or any sort of repercussions from using a javascript automator to play a Steam Sale game.
