### ISSUE TITLE
Not Working on Firefox

### ISSUE THREAD

**Issue by pepe1987** [coryshaw1/saliens-hack#7]
`ReferenceError: unsafeWindow is not defined`

Please revert https://github.com/coryshaw1/saliens-hack/issues/3

**Comment by coryshaw1** [comment]
You have to use a userscript extension for the unsafeWindow to work. Please follow the installation instructions from the readme. If you don't want to use an extension, you'll have to manually remove `unsafeWindow.requestAnimationFrame = c => { setTimeout(c, 1000 / 60); };` from the script yourself

**Comment by Wiethoofd** [comment]
Why not add `if(unsaveWindow)` before the line setting the requestAnimationFrame?

**Comment by coryshaw1** [comment]
Would help the reports haha, good call!

**Comment by pepe1987** [comment]
I am using `Tampermonkey`, I made it work by setting 10 seconds, maybe my internet connection an my pc are not the best.

I am closing this for now.

Thanks!
